server:
  port: 8010

spring:
  application:
    name: eureka-product

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/

feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,hystrix.stream
