server:
  port: 7002

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:7001/eureka/

spring:
  application:
    name: eurka-server
